- source: TEST
  user_name: example@gmail.com
  password: nadxyhojstpvhang
  smpt:
    host: smtp.googlemail.com
    port: 587

- source: SAMPLE
  user_name: example@gmail.com
  password: nadxyhojstpvhang
  smpt:
    host: smtp.googlemail.com
    port: 587
