- source: TEST
  user_name: shkabuthahir@gmail.com
  password: nadxyhojstpvhang
  smpt:
    host: smtp.googlemail.com
    port: 587

- source: SHASTI-OUTSOURCING
  user_name: shkabuthahir@gmail.com
  password: nadxyhojstpvhang
  smpt:
    host: smtp.googlemail.com
    port: 587
